import Image from 'next/image'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Main from '@/components/Main'
import About from '@/components/About'
import Footer from '@/components/Footer'
import Team from '@/components/Team.'
import Services from '@/components/Services'


export default function Home() {
  return (
    <div className='bg-white'>
      <Head>
        <title>Octa-Tech</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icons' href='/octa-tech.svg' />
      </Head>
      <Navbar />

      <Main />

      <About />

      <Team />

      <Services />

      <Footer />

    </div>
    
    
  )
}
